In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('carprices.csv')

df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = df
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [4]:
z = le.classes_

In [5]:
z[1]

'BMW X5'

In [6]:
x = dfle.drop(['Sell Price($)'],axis= 1)
x

Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [7]:
y = dfle['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2)

In [9]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [10]:
scaler = MinMaxScaler()

In [11]:
scaler.fit(x_train)

MinMaxScaler()

In [12]:
X_train_scaled = scaler.transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [13]:
X_train_scaled

array([[1.        , 0.78571429, 0.8       ],
       [0.5       , 0.        , 0.        ],
       [0.5       , 0.39285714, 0.4       ],
       [0.        , 0.30357143, 0.4       ],
       [0.        , 0.42857143, 0.4       ],
       [0.5       , 0.19642857, 0.2       ],
       [1.        , 0.57142857, 0.6       ],
       [1.        , 0.42857143, 0.4       ],
       [0.        , 1.        , 1.        ],
       [0.        , 0.66071429, 0.6       ]])

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()

In [16]:
model.fit(X_train_scaled,y_train)

LinearRegression()

In [17]:
model.score(X_test_scaled,y_test)

0.8857741421705813

In [19]:
model1 = LinearRegression()

In [31]:
model1.fit(x_train,y_train)

LinearRegression()

In [32]:
model1.score(x_test,y_test)

0.8857741421705816

In [34]:
model1.predict([[1,40000,3]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([34475.62108534])

In [42]:
X_new = np.array([[1,40000,3]])
X_new_scaled = scaler.transform(X_new)
y_pred = model.predict(X_new_scaled)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [43]:
y_pred

array([34475.62108534])